### ISSUE TITLE
Creating Repository

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#1]
### User Story
As a developer i can create a new GitHub repository for my project so that i am able to begin the project

#### Tasks

- [x] Go to github and create a new repository
- [x] Enter a meaningful name for the repository
- [x] Create a project for the repository
- [x] Add in the user stories and epics
- [x] Break the user stories and epics into must, should, could and won’t have

#### Acceptance Criteria

- [x] Successfully create github repository 
- [x] User stories, tasks and epics added
- [x] Project successfully created
- [x] User stories given labels of must, should, could and won’t have

**Comment by GMontaque** [comment]
added must have label

**Comment by GMontaque** [comment]
add to 1st iteration
