### ISSUE TITLE
Account Registration

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#10]
### User Story
As a user I can register an account for the website so that I can access certain sections of the website

#### Tasks

- [x] Add in user registration link
- [x] Create a model for the user database
- [x] Add html validation to form required fields
- [x] Create html template

#### Acceptance Criteria

- [x] There is a sign up link in the nav bar
- [x] Clicking registration takes you to the registration page
- [x] Clicking submit will submit the form
- [x] The sign up page has a form to complete
- [x] When completed pop up message appears
- [x] User can register an account
- [x] User redirected to homepage after registration
