### ISSUE TITLE
User Log In

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#11]
### User Story
As a user I can log into the website so that I can get access to the site whenever I wish

#### Tasks

- [x] Create log in button
- [x] Create log in form
- [x] Get confirmation message once logged in
- [x] Display correct navbar links depending on user permission

#### Acceptance Criteria

- [x] Navigation bar contains log in button
- [x] Clicking log in button takes you to the log in form
- [x] The login form contains fields like username and password
- [x] Log in form contains log in button
- [x] Confirmation message when user is logged in
- [x] Correct navbar is displayed depending on user access
