### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#12]
### User Story
As a user I can reset my password if I have forgotten it so that I can get back into the site

#### Tasks

- [x] Log in button contains reset option
- [x] Update password reset template html
- [x] Confirmation message when password reset successfully 

#### Acceptance Criteria

- [x] Log in form contains password reset button
- [x] Clicking password reset button takes you to a password reset form
- [x] Password reset asks for email amd memorable name.
- [x] Form has submit button
- [x] When submitted a message is shown
