### ISSUE TITLE
Admin User Account Control

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#13]
### User Story
As a admin user I can have overall control of user accounts so that I can manage them and the permissions of the users 

#### Tasks

- [x] Link the webpage with admin account.
- [x] Admin screen should have delete function

#### Acceptance Criteria

- [x] Admin can delete user account
- [x] Navigation link to admin portal
- [x] Confirmation message when user profile deletes or changed
