### ISSUE TITLE
Log In and Out message

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#14]
### User Story
As a user I can see the correct on-screen message when logging in and out so that it is clear what state I am in i.e logged in or out

#### Tasks

- [x] Create a pop up screen for log in and out
- [x] Link on screen message to log in and out
- [x] Track user status to see if user is logged in or out

#### Acceptance Criteria

- [x] On screen message changes depending on user logged in status
- [x] Message created from popup modal
- [x] Background darkens
