### ISSUE TITLE
Clan Rep Access

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#15]
### User Story
As a clan rep I can log in and be given the access of a clan rep so that I can create my clan page, raise tickets and have (C.R.U.D) functionality on the clan page

#### Tasks

- [x] User log in is checked that user is a clan rep
- [x] Navbar shows clan creation tab
- [x] Clan rep can create clan page
- [x] Clan rep can update clan page
- [x] Clan rep can delete clan page
- [x] Create model for clan page
- [x] Create app for clan page

#### Acceptance Criteria

- [x] user account checked for clan rep access
- [x] navigation bar displays clan creation link in nav bar
- [x] clicking clan creation navigation link takes you to clan creation form
- [x] clan page can be updated or deleted – C.R.U.D
- [x] confirmation popup when a change made or page created
