### ISSUE TITLE
Default Clan Page Image

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#16]
### User Story
As a developer I can set as default image when a clan page is created so that the site is more visually appealing and breaks up the text

#### Tasks

- [x] create static folder
- [x] static folder contains images to be used
- [x] images link with clan page 

#### Acceptance Criteria

- [x] Static folder contains default image list
- [x] Default images are used as a base
- [x] Image is displayed when user page loads
- [x] Image is correctly styled
