### ISSUE TITLE
Clan Page Creation

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#17]
### User Story
As a clan rep I can create a clan page for my clan so that it is visible on the website to all users with the clan information

#### Tasks

- [x] create a model for the database
- [x] model created for clan pages
- [x] create a view 
- [x] create an app called clan page
- [x] create html template

#### Acceptance Criteria

- [x] Clan pages are stored in a database once created
- [x] App called clan page created
- [x] Html template for clan page created
- [x] The clan page should display the clan information
- [x] The clan page can be seen on the website
- [x] Clan page contains accepted game requests
- [x] Clan page linked to clan rep account for that clan
