### ISSUE TITLE
Clan Rep Upload Image

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#18]
### User Story
As a clan rep I can upload images related to my clan so that I can enhance the look and feel of my clan page

#### Tasks

- [x] Make sure clan database has image field
- [x] Use static image files for default
- [x] Add images to clan page when they load
- [x] Ability to upload images when clan page created

#### Acceptance Criteria

- [x] Clan database contains image storage field
- [x] Default static image is used if clan rep provides no image for clan page
- [x] Images added to clan page are visible when page loads
- [x] Clan rep can upload images when clan page created
- [x] Images can be updated
