### ISSUE TITLE
Clan Social Media Links

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#19]
### User Story
As a clan rep I can add in the clan’s social media links so that I can provide more details and a way for people who want to join the clan to join

#### Tasks

- [x] Add a social media field to the clan database
- [x] Ability to add social links when clan page created
- [x] Ability to update social links
- [x] Add current and up to date links 

#### Acceptance Criteria

- [x] Clan database contains social media field
- [x] Social media links are stored under the database
- [x] Clan rep can add, upload and change social media links
- [x] Social media links take the user to the correct page
- [x] Social media links can be seen by all on the clan page
