### ISSUE TITLE
folder structure creation

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#2]
### User Story
As a developer I can create the correct folder structure so that I can organise my code correctly 

#### Tasks

- [x] create the root folder in the project
- [x] create a static folder
- [x] add in the requrimetns.txt file
- [x] create evn.py file
- [x] update gitignore file

#### Acceptance Criteria

- [x] Successfully cerate all folders and files needed for the project.
- [x] Root folder is created.
- [x] Requirmetns.txt created.
- [x] Env.py file created.
- [x] .gitignore updated correctly 
- [x] Static folder created.

**Comment by GMontaque** [comment]
added must have label
