### ISSUE TITLE
Admin User - Clan Page C.R.U.D

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#20]
### User Story
As a admin user I can add, update and delete sections of a clan page so that information is kept up to date and relevant and improve user experience

#### Tasks

- [x] Admin user has access to all clan pages
- [x] when clan page data is updated, it is shown on clan page
- [x] create view for update, delete and add
- [x] confirmation message sent when something is changed

#### Acceptance Criteria

- [x] Admin user can access all clan pages
- [x] When clan page is updated this should be seen immediately on the page refresh
- [x] Admin user has C.R.U.D ability 
- [x] Confirmation message when change completed
