### ISSUE TITLE
Admin User - Clan Page Check

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#21]
### User Story
As a admin user I can check a clan page before it goes live so that I can check the content of the page, any errors or spam and in keeping with the website purpose

#### Tasks

- [ ] Create clan page creation notification for Admin
- [ ] Preview clan page loaded for admin to review
- [ ] Create an rejected button so clan does not go live 
- [ ] Create an accepted button so clan page goes live 
- [ ] Create clan rep notification of admin decision yes or no

#### Acceptance Criteria

- [ ] Notification of clan creation appears for admin
- [ ] A clan page preview is shown to admin
- [ ] Admin can accept or reject page going live
- [ ] Admins decision is sent as a notification to the clan rep
