### ISSUE TITLE
Clan Page Form Validation

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#22]
### User Story
As a clan rep I can see validation prompts when completing the clan form so that I can tell when an input field has not been completed properly or information missed.

#### Tasks

- [x] Add in html form validation
- [x] Create clear input field labels
- [x] Add in Django form validation
- [x] Create clear validation prompts

#### Acceptance Criteria

- [x] Clan page shows validation prompts if user tries to submit when there is an error
- [x] Validation message is clear and describe the issue
- [x] Form validation checks each field for input data and data type
- [x] Form validation stops submission of the form
