### ISSUE TITLE
Game Request Link Visible

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#23]
### User Story
As a clan rep I can see the game requests link in my navigation bar so that I can access the game request page

#### Tasks

- [x] Cerate game request app
- [x] Create a model
- [x] Game request to appear in navigation bar
- [x] Link with game request page

#### Acceptance Criteria

- [x] Game request app is created and connected with database
- [x] Game request is hidden with function condition and appears when clan rep logs in
- [x] Clicking game request link send you to game request page
- [x] Styling used is in keeping with other links in navigation bar
