### ISSUE TITLE
Raise Game Request

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#24]
### User Story
As a clan rep I can raise a game request on behalf of my clan so that we can challenge other clans to competitive or friendly games

#### Tasks

- [x] Create Django app for game requests
- [x] Create html template
- [x] Create form
- [x] Create model database for form
- [x] Add validation to form
- [x] Create submit button

#### Acceptance Criteria

- [x] Game request app is created.
- [x] Html page contains game request form.
- [x] Game request form includes all relevant fields as per ERD database diagram.
- [x] Game request form includes html validation.
- [x] A submit button is included.
- [x] Game requests are only visible to be requested by a signed in clan rep
