### ISSUE TITLE
Access Game Request Form

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#25]
### User Story
As a clan rep I can access the game request form so that I can send a game request to another clan

#### Tasks

- [x] Create game request tab for logged in clan reps
- [x] Game request to appear in clan rep navbar
- [x] Game request url linked with game request html template

#### Acceptance Criteria

- [x] Game request link can be seen in the navigation bar.
- [x] Game request only appears for clan reps
- [x] Game request link is connected to html template page.
- [x] Game requests are linked with database.
