### ISSUE TITLE
Complete Game Request Form

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#26]
### User Story
As a clan rep I can fill out the form for a game request so that I can provide the necessary information to the other clan to then decide to accept or not

#### Tasks

- [x] Create form with correct field and field types
- [x] Create form model.
- [x] Connect form with html template.
- [x] Add link to game request page.
- [x] Add html authentication.

#### Acceptance Criteria

- [x] Clicking game request link opens game request form.
- [x] User can input values into the game request form.
- [x] Form field such as name only accept letters.
- [x] Confirmation message when game request sent.
- [x] Game request form is correctly styled. 
- [x] Game requests are stored in the database
