### ISSUE TITLE
Game Request Form Submission

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#27]
### User Story
As a clan rep I can only submit the form when all required fields are complete so that I make sure to pass across all the information the other clan would need

#### Tasks

- [x]	Prompt user if field is not completed
- [x]	Grey out button till all field completed

#### Acceptance Criteria

- [x]	Clan rep is prompted when a field is missed
- [x]	Submit button is greyed out until all fields have data
- [x] Form has clear instructions on how to complete the form
