### ISSUE TITLE
Game Request Confirmation Message

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#28]
### User Story
As a clan rep I can see a confirmation message so that I can tell when the request has been submitted correctly

#### Tasks

- [x] Link confirmation message with form completion.
- [x] Code popup model to appear using javascript

#### Acceptance Criteria

- [x] Popup modal appears for confirmation message.
- [x] Confirmation message linked with form submission.
- [x] JavaScript used to display pop up message
