### ISSUE TITLE
Receive Game Request

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#29]
### User Story
As a clan rep I can receive a game request from another clan so that I can either accept or decline the request

#### Tasks

- [x] Game request added to notification page
- [x] Display new game request on click
- [x] Implement a feature to allow clan reps to accept or decline game requests
- [x] Confirmation popup if accept or decline

#### Acceptance Criteria

- [x] Displayed notifications show accept or decline button
- [x] Game reqeusts show in notification page
- [x] Game requests include game info such as time, date and opponent
- [x] Clicking accept or decline button update status of game request
