### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#3]
### User Story
As a developer i can deploy my site to Heroku so that I can check all necessary tools and software is included in the site

#### Tasks

- [x] Sign in or create Heroku app
- [x] Link GitHub repository to Heroku
- [x] Deploy the site to Heroku
- [x] Update config vars
- [x] Set debug to false
- [x] Access site through the browser

#### Acceptance Criteria

- [x] The Heroku app is created
- [x] The GitHub repository is linked with the Heroku app
- [x] The site is successfully deployed to Heroku
- [x] Config var has been updated.
- [x] Debug is set to false
- [x] Website appears in the browser.

**Comment by GMontaque** [comment]
added must have label
