### ISSUE TITLE
Game Request Notification

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#30]
### User Story
As a clan rep I can get a notification so that I can tell when I have a new game request

#### Tasks

- [x] Implement a notification system for new game requests
- [x] Integrate the notification system with the user accounts so that notifications are sent to the correct clan rep
- [x] Implement a feature to display notifications for clan rep's

#### Acceptance Criteria

- [x] New notifications are shown in the notification page
- [x] Clan reps have their own notification system
