### ISSUE TITLE
Game Request Acceptance

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#31]
### User Story
As a clan rep I can see accepted game requests so that I can see upcoming game request that have been accepted

#### Tasks

- [x] Create html table to display accepted games
- [x] Included accepted games in clan page
- [x] Table connected to database of accepted games

#### Acceptance Criteria

- [x] A clan rep can view accepted game requests for their clan
- [x] Accepted games are displayed on clan page
- [x] Accepted games shown in html table
- [x] Accepted games are sortable by the column headers
