### ISSUE TITLE
User Accounts Database

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#32]
### User Story
As a developer I can create a database for user accounts so that users can log in and out as they wish

#### Tasks

- [x] Create user database
- [x] Create user log in
- [x] Create user log out

#### Acceptance Criteria

- [x] Created database holds user accounts
- [x] User can log in and out
