### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#33]
### User Story
As a developer I can create a database schema so that I have a blueprint for how the databases should interact

#### Tasks

- [x] Create data model image
- [x] Data model will contain data type of different fields
- [x] Correct labels used

#### Acceptance Criteria

- [x] The data scheme is correctly created
- [x] Data scheme is used as the database blueprint
- [x] Data schema columns have correct and consistent labels
- [x] Data model contains correct data types of fields
