### ISSUE TITLE
Clan Page Database Creation

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#34]
### User Story
As a developer I can create a database for the clan pages so that any clan rep who creates a page is stored and can be viewed

#### Tasks

 - [x] Create model
- [x] Create view
- [x] Create url path
- [x] Link with database.

#### Acceptance Criteria

- [x] Clan pages database is created
- [x] Database has correct fields
- [x] Database stores multiple entries 
- [x] Clan pages can be added, updated and deleted from the database
- [x] Database can be called and the data used
