### ISSUE TITLE
Game Request Database

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#35]
### User Story
As a developer I can create a database for game requests so that clan reps can send and receive requests

#### Tasks

-  [x] Create model
-  [x] Create view
-  [x] Create url path
-  [x] Link with database

#### Acceptance Criteria

-  [x] Database for game requests created
-  [x] Model for database created with correct fields
-  [x] A view.py is created to display the information
-  [x] URL path created to view each game request
