### ISSUE TITLE
Notification Database

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#36]
### User Story
As a developer I can create a database for notifications so that clan reps and admin can see when they have a new message

#### Tasks

- [x] Create model
- [x] Create view
- [x] Create url path
- [x] Link with database

#### Acceptance Criteria

- [x] Database for notifications created
- [x] Model for database created with correct fields
- [x] A view.py is created to display the information
- [x] URL path created to view notifications
