### ISSUE TITLE
About Page - C.R.U.D

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#37]
### User Story
As a developer I can create a database for the about page so that the admin can use CRUD to update and delete information

#### Tasks

- [ ] Create model
- [ ] Create view
- [ ] Create URL path
- [ ] Link with database
- [ ] CRUD access for admin only

#### Acceptance Criteria

- [ ] Database for about page created
- [ ] Model for database created with correct fields
- [ ] A view.py is created to display the information
- [ ] Url path created to view about page from navigation bar
- [ ] Database entry displays on html about page
