### ISSUE TITLE
Notifications link in Nav Bar 

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#38]
### User Story
As a clan rep I can see the notifications link in the nav bar so that I can easily access the notifications tab

#### Tasks

- [x] Add a notifications tab to the navigation bar.
- [x] Notifications tab linked to user clan rep account.

#### Acceptance Criteria

- [x] Clan reps should be able to see notifications link in navigation bar
- [x] Notification tab clearly labelled
- [x] Notification tab always visible in navigation bar
- [x] Not visible when not signed in as clan rep
