### ISSUE TITLE
Notification Link Colour Change

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#39]
### User Story
As a clan rep I can see that the notifications link has changed colour so that I can tell when I have a new unread message

#### Tasks

 - [ ] Create different css styles for notifications.
 - [ ] Check a clan reps notification when they log in.
 - [ ] Use fontawesome for notification image.

#### Acceptance Criteria

 - [ ] CSS style created for notification colour change
 - [ ] CSS style clearly named
 - [ ] CSS styling updated by JavaScript
 - [ ] Notifications link is clear and easy to read
 - [ ] Fontawesome is installed and used correctly 
 - [ ] JavaScript toggles CSS style classes
