### ISSUE TITLE
Website Navigation

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#4]
### User Story
As a user I can easily find my way around the site so that I can access the different sections with no issues

#### Tasks

- [x] Follow wireframe for website design.
- [x] Create links with the same styling.
- [x] Create site using UX design principles 

#### Acceptance Criteria

- [x] Wireframe has been followed in the design and layout.
- [x] Navigation bar has a set style across all pages
- [x] Website has a consistent theme and styling across all pages
- [x] Correct font and colours have been used
