### ISSUE TITLE
Notification Link View

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#40]
### User Story
As a clan rep I can click on the notifications link so that I can view the unread notification

#### Tasks

- [x] Notifications link shows in nav bar
- [x] Notifications link is a clickable link.

#### Acceptance Criteria

- [x] Clicking notification link takes you to notifications page
- [x] Notification link clearly labelled 
- [x] Link is clickable
