### ISSUE TITLE
Notification - Shown Game Requests

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#41]
### User Story
As a clan rep I can click on the notification link and be shown game requests so that I can decided whether to accept or decline the game request

#### Tasks

 - [x] Create feature to display unread notifications
 - [x] Show notifications marked as read
 - [x] Create table format to display notifications

#### Acceptance Criteria

 - [x] Notification page displays game requests
 - [x] Game request contain relevant info
 - [x] Notifications are displayed in a table layout
