### ISSUE TITLE
Notification Link  - Access

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#42]
### User Story
As a user I can not access or see the notifications tab unless I am logged in so that users with only the correct authority can view the page

#### Tasks

- [x] Create conditional function for notifications
- [x] Add into html template

#### Acceptance Criteria

- [x] User account checked for clan rep status
