### ISSUE TITLE
Send Admin Ticket

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#43]
### User Story
As a clan rep I can send a ticket to the admin team so that so that I can get support and raise any issue

#### Tasks

 - [x] Create ticket model
 - [x] Create admin ticket form
 - [x] Create html template
 - [x] Create Form submission button

#### Acceptance Criteria

 - [x] Clan rep can send ticket to admin
 - [x] Ticket model contains correct fields
 - [x] Admin ticket form contains submit button
 - [x] Confirmation popup when ticket sent
 - [x] Ticket form has html validation
