### ISSUE TITLE
Ticket Notification

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#44]
### User Story
As a clan rep I can get a notification from admin about by ticket so that I can tell when it has been actioned

#### Tasks

 - [ ] Link with current clan rep notifications tab
- [ ] Print simple message to clan rep
- [ ] Notification tab informs clan rep there is a message

#### Acceptance Criteria

- [ ] Notification link changes colour to show there is a new message
- [ ] Clicking notification link shows response from admin
- [ ] Response is a simple on-screen message
- [ ] Response message is styled
