### ISSUE TITLE
View Clan Rep Tickets

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#45]
### User Story
As a admin user I can view tickets which have been raised so that I can provide support to the clan rep’s

#### Tasks

 - [x] create model
 - [x] create ticket page
 - [x] view tickets on admin ticket page
 - [x] can click on ticket link

#### Acceptance Criteria

 - [x] Can view tickets raised by clicking tickets link
 - [x] Ticket model included correct fields
 - [x] Ticket page has tickets laid out clearly
 - [x] Shows list of all open tickets
