### ISSUE TITLE
Ticket Confirmation Message

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#46]
### User Story
As a admin user I can send confirmation to the clan reps so that they can see when a ticket has been actioned

#### Tasks

 - [x] Ticket to contain 3 buttons
 - [x] Admin ticket contains completion button
 - [x] Admin ticket contains decline button
 - [x] Confirmation notification sent

#### Acceptance Criteria

 - [x] Status of ticket is set to confirmed for the clan rep when completed
 - [x] Ticket has completed and declined buttons
 - [x] Status of ticket is set to decline for the clan rep when rejected
 - [x] Confirmation of notification is sent to clan rep
