### ISSUE TITLE
See Ticket Notifications

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#47]
### User Story
As a admin user I can see that the notifications link has changed colour so that I can tell when I have a new unread message

#### Tasks

 - [ ] Create notifications link 
 - [ ] Conditional function linked to notifications tab colour created
 - [ ] CSS style created for different notification state

#### Acceptance Criteria

 - [ ] Notification link changes colour when a new ticket is sent
 - [ ] Notification link is visible and correctly styled
 - [ ] Conditional function that changes the navigation link colour
 - [ ] CSS style created for navigation link
 - [ ] Only admin can see tickets received
