### ISSUE TITLE
Clear Error Message

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#48]
### User Story
As a user I can receive clear and helpful error messages so that I am able to see when something has gone wrong

#### Tasks

 - [x] Create custom popup messages for errors
 - [x] Create custom error messages for different errors
 - [x] Include html validation in forms
 - [x] Include error handling in JavaScript code
 - [x] Include error handling in python code

#### Acceptance Criteria

 - [x] A popup message appears when an error happens
 - [x] There should be a custom message depending on the error
 - [x] Html validation should be included on all forms and fields
 - [x] Error handling is included in the python code 
 - [x] Error message is clear and helpful to read and understand
 - [x] Error message is accurate
