### ISSUE TITLE
Stop Errors Happening

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#49]
### User Story
As a developer I can stop errors from occurring so that the user experience is not impacted

#### Tasks

 - [x] Complete unitest on python code
 - [x] Complete manual testing of code

#### Acceptance Criteria

 - [x] Unit test is completed on all python code
 - [x] Manual testing carried out on completed project
 - [x] Code is error free
 - [x] Any errors found are logged
