### ISSUE TITLE
Visible clickable navigation bar

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#5]
### User Story
As a user I can  see the navigation bar and can click on the links so that I am taken to the correct page

#### Tasks

- [x] Create the navigation bar
- [x] Create links for all pages within navigation bar
- [x] Include navigation bar in all html templates
- [x] Navigation bar should be responsive

#### Acceptance Criteria

- [x] The navigation bar is visible on all html pages.
- [x] The navigation bar has all the correct links. 
- [x] The navigation bar is responsive across different screens
- [x] The navigation bar informs user what page then are on
