### ISSUE TITLE
Error Catching

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#50]
### User Story
As a developer I can implement error catching so that the I can understand where the error is coming from and fix it

#### Tasks

 - [x] Use try expect in python code
 - [x] Include console log when creating site and remove from final production

#### Acceptance Criteria

 - [x] Try expect used in python code
 - [x] Console log is used when testing sections of code
 - [x] Console log and commented out code removed from final product
 - [x] Errors are caught and fixed, if not logged to be resolved
