### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#51]
### User Story
As a user I can expect to be shown a message if an incorrect URL is inputted so that I can tell when an error has occurred and what to do

#### Tasks

 - [x] Create 404 error page
 - [x] Link 404 page in the url’s
 - [x] Write custom error page

#### Acceptance Criteria

 - [x] 404 page is created
 - [x] 404 page is displayed when incorrect URL inputted
 - [x] 404 page contains custom error message
 - [x] Page contains home button to take user back to the site
