### ISSUE TITLE
Error Message format and style

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#52]
### User Story
As a user I can expect consistent error message format and style so that I can easily understand and notice errors

#### Tasks

 - [x] create a style and format standard for all messages
 - [x] use clear and concise language

#### Acceptance Criteria

 - [x] System displays error messages using the correct style
 - [x] System has defined style and format standard
 - [x] The wireframe design plan can be seen to have been followed
 - [x] Errors have clear language
 - [x] Clear for a user to see the error message
