### ISSUE TITLE
Website User Access

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#53]
### User Story
As a developer I can stop users from accessing sections of the website without correct authority so that the site is kept secure

#### Tasks

- [x] User specific sections to be contained within conditional functions
- [x] User access checked when logged in – role base access
- [x] User specific sections not shown when webpage loads

#### Acceptance Criteria

- [x] Code is added to check users account on sign in
- [x] Conditional functions use values from user database to check what can be shown
- [x] Website does not display user-specific sections when website loads
- [x] When user logs out, webpage reverts to initial state and removes user specific information and links
