### ISSUE TITLE
Manaul Testing

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#54]
### User Story
As a developer I can conduct manual testing on all parts of the website so that I can locate and solve any issues or bugs before the website is made live

#### Tasks

 - [x] create a testing plan
 - [x] identify parts of the site that need manual testing
 - [x] create list of test cases
 - [x] document test results
 - [x] check all functions
 - [x] check website responsive
 - [x] fix bugs
 - [x] document issues and bugs

#### Acceptance Criteria

 - [x] A detailed test plan is created
 - [x] Manual testing sections are identified and noted down
 - [x] Test cases are created to check the site for all possible cases
 - [x] All test results are documented along with issues and bugs
 - [x] Sight features checked
 - [x] Website responsiveness is tested on different browsers and devices
 - [x] Found errors are fixed
