### ISSUE TITLE
Log Testing

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#55]
### User Story
As a developer I can log the testing so that I can demonstrate that comprehensive testing has been carried out

#### Tasks

 - [x] create markdown table to show tests
 - [x] table should state the test, the expected outcome and result
 - [x] record all unit testing in python
 - [x] record what sections tested
 - [x] document issues and how they were resolves
 - [x] write testing code

#### Acceptance Criteria

 - [x] A markdown table is created which contains all tests
 - [x] Table is broken down into test, expected outcome and result
 - [x] Separate section shows unitest results
 - [x] A section is included for bugs and how they were resolved
 - [x] Test documentation is clearly laid out
