### ISSUE TITLE
Test Internal and External links

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#56]
### User Story
As a developer I can test all internal and external links on the website so that I can make sure a user can navigate the site and is taken to the correct webpage/website

#### Tasks

 - [x] Test external links go to correct site
 - [x] Test internal links go to correct page
 - [x] Fix and retest and broken links

#### Acceptance Criteria

 - [x] Verification checks done on all external links to check they open to correct site
 - [x] Verification checks done on all internal links to check they go to the correct page
 - [x] Any broken links have been fixed
 - [x] Links tested on different devices and browsers
