### ISSUE TITLE
Form Test

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#57]
### User Story
As a developer I can test all forms and fields a user has to complete so that I can make sure the correct information is stored and the user has a good experience

#### Tasks

 - [x] Test all forms work correctly.
 - [x] Test form fields accept the correct data and data format.
 - [x] Test form validation.
 - [x] Test error handling.
 - [x] Test form content submitted correctly.
 - [x] Form should reset after being completed.

#### Acceptance Criteria

 - [x] Form fields tested to check validation works.
 - [x] Form and form fields checked to make they work correctly.
 - [x] Form fields data type checked to only allow certain data type.
 - [x] Check form can be submitted correctly.
 - [x] Check user gets correct error message if there is an error with the form.
 - [x] Check form meets accessibility guidelines. 
 - [x] Form is responsive.
