### ISSUE TITLE
Browser Test

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#58]
### User Story
As a developer I can check the website works correctly in different browsers and devices so that a user has a good experience, and the site works as expected.

#### Tasks

 - [x] Test website on different browsers.
 - [x] Test website on different devices i.e mobile and pc.
 - [x] Test website on different screen sizes.
 - [x] Test the website as different users i.e admin, clan rep.
 - [x] Test website loads correctly. 
 - [x] Test website styling is correct. 
 - [x] Test website functions as expected

#### Acceptance Criteria

 - [x] Website has been tested on all mainstream browsers to check the site works as expected. 
 - [x] The website has been tested on mobile devices and desktop devices to check the site works as expected. 
 - [x] The website has been tested on different screen sizes to check the site works as expected. 
 - [x] Website is tested to check it works regardless of the user type that is signed in.
 - [x] Styling is checked to make sure it matches with the wireframe plan.
