### ISSUE TITLE
Python Unittest

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#59]
### User Story
As a developer I can pass the python code through unittest so that I can thoroughly check the code has no errors and meets all python standards*

#### Tasks

 - [x] Write unit tests for all functions in the code
 - [x] Import unittest
 - [x] Make sure tests cover function usage.
 - [x] Create mock objects to test user account.
 - [x] Create mock object to test form submission.
 - [x] Create mock data to test clan page creation.
 - [x] Log test results in readme.

#### Acceptance Criteria

 - [x] Unit tests are created for all functions to check they work as expected.
 - [x] Python code checked that it meets python standards.
 - [x] Tests cover all possible function usage and scenarios including obscure one.
 - [x] Mock data is used to test functions against database.
 - [x] All results are logged in a readme file.
 - [x] Tests are written in a clean and concise way to test different functions.
