### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#6]
### User Story
As a user I can find the about page so that I can learn more information about the site

#### Tasks

- [ ] Create the app called “about”
- [ ] Add the app to the urls.py file
- [ ] Create a view in the about app
- [ ] Link the about app to the static folder html page
- [ ] Create database in model.

#### Acceptance Criteria

- [ ] You can access the about page from the navigation bar
- [ ] The about page shows the relevant information about the site
- [ ] The about page is linked to the static HMTL page
- [ ] There is an about app created, with a view model and template
- [ ] The about page is linked to the related database
