### ISSUE TITLE
JavaScript JEST Test

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#60]
### User Story
As a developer I can pass the JavaScript code through jest so that I can thoroughly check the code has no errors and meets all standards

#### Tasks

 - [ ] Install JEST testing.
 - [ ] Write test cases for JavaScript functions.
 - [ ] Write expected outputs and check against function tests.
 - [ ] Record the results of tests.

#### Acceptance Criteria

 - [ ] Test cases created to test JavaScript functions
 - [ ] Expected outputs are written for each test and then checked against actual output
 - [ ] Tests are correctly record in readme file
 - [ ] JavaScript code check it meets industry standard
 - [ ] Tests function titles are clear and well written
