### ISSUE TITLE
HTML and CSS Validator

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#61]
### User Story
As a developer I can use a validator on the HTML and CSS code so that I can thoroughly check the code has no errors and meets all standards.

#### Tasks

 - [x] Pass the html through a validator.
 - [x] Correct any errors shown in validator.
 - [x] Pass the CSS against the CSS validator.
 - [x] Correct any errors found in validator.
 - [x] Document results of html and CSS validator.

#### Acceptance Criteria

 - [x] Html is checked against validator. 
 - [x] CSS is checked against validator. 
 - [x] Any errors found are corrected.
 - [x] Results of the tests are well documented in Readme. 
 - [x] Html form validation is checked.
 - [x] Sematic html is correctly used.
