### ISSUE TITLE
Lighthouse Test

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#62]
### User Story
As a developer I can use lighthouse to test the website so that I can check the performance, accessibility, SEO and best practices up to the standard required.

#### Tasks

 - [x] Run lighthouse in the chrome browser.
 - [x] Record the results.
 - [x] Run lighthouse on pagespeed insights.
 - [x] Record the results.
 - [x] update and correct code as per lighthouse results.

#### Acceptance Criteria

 - [x] Lighthouse is used to test website for performance, accessibility, SEO, and best practices.
 - [x] The results of the Lighthouse test are recorded in the readme.
 - [x] PageSpeed Insights is used to test website for performance, accessibility, SEO, and best practices.
 - [x] The results of the PageSpeed Insights test are recorded in the readme.
 - [x] Code is updated and correct code as per Lighthouse and PageSpeed Insights results.
