### ISSUE TITLE
Locate Clan Pages

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#7]
### User Story
As a user I can find the different clan pages so that I can view the different clans that play hell let loose

#### Tasks

- [x] Create an app called clan.
- [x] Create a model within the clan app.
- [x] Create a view.
- [x] Create template.
- [x] Populate template with clan database results.

#### Acceptance Criteria

- [x] Clan page can be accessed from the home page
- [x] Home page displays all clan pages from the database
- [x] Clicking on a clan name takes you to their clan page
- [x] A clan page HTML template is created
- [x] Custom URL path created using clan name
