### ISSUE TITLE
Base User Create Account

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#74]
### User Story
As a base user I can create an account with basic access so that I can comment under clan pages

#### Tasks

 - [ ] Create a log in page in the nav bar
- [ ] Link registration with database
- [ ] Log in page has an option for a basic user
- [ ] Confirmation message when user registered

#### Acceptance Criteria

- [ ] Website has sign up link in navigation bar
- [ ] Clicking log in takes you to sign up page
- [ ] Registration page has form to complete
- [ ] Form has submitted button
- [ ] Successful message shown when for submitted 
- [ ] User redirected to website
