### ISSUE TITLE
General User Access

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#76]
### User Story
As a general user I can only access the ability to comment so that I cannot make changes or update content on the website

#### Tasks

 - [ ] Create Users account access checked when logging in
 - [ ] Conditional functions used to check user access
 - [ ] Comment section can be seen by general user

#### Acceptance Criteria

 - [ ] General user can find comments section under each clan page
 - [ ] User account checked for level of access when logging in
 - [ ] Functions used hide sections user should not access
