### ISSUE TITLE
General User C.R.U.D access

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#77]
### User Story
As a general user I can update or delete a comment so that I can manage my own comments and content

#### Tasks
 - [ ] create edit button in comments section
 - [ ] create delete button in comments section
 - [ ] link with JavaScript to populate comment with previous comments
 - [ ] popup confirming comment change or deleted

#### Acceptance Criteria
 - [ ] Comment section contains edit button under each comment post
 - [ ] Comment section contains delete button under each comment post
 - [ ] If user presses edit, the text field contains the previous comment
 - [ ] Popup message shows when change or deletion completed
