### ISSUE TITLE
General User comment check

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#78]
### User Story
As a admin I can review a general user comment so that I can check the content before having it posted on the webpage

#### Tasks

 - [ ] create a html template to be able to see user comments
 - [ ] create button to either approve or reject comment
 - [ ] inform user if comment is approved or rejected
 - [ ] user comments broken down by user

#### Acceptance Criteria

 - [ ] Html page displays user comments under review
 - [ ] Each comment has a button to approve or reject comment
 - [ ] Messge sent to user confirming result
 - [ ] Comments laid out in a clear logical manner
