### ISSUE TITLE
Clan Search Bar

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#8]
### User Story
As a user I can user the search bar so that I can find clans by their name

#### Tasks

- [ ] Create a search bar in html
- [ ] Link search bar to database clan names
- [ ] Add a submit button
- [ ] Add JavaScript eventlistener to listen for submission

#### Acceptance Criteria

- [ ] Search bar is visible on home page
- [ ] Search bar is large enough to fit clan name
- [ ] Search bar is linked to database
- [ ] Search bar has submit button
- [ ] Eventlistener attached to submit button
- [ ] If no result is returned the system should inform the user
