### ISSUE TITLE
Admin Ticket Non Clan Representative

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#81]
### User Story
As a signed up user I can view the notifications page like a clan representative user so that I can raise tickets to send admin and see my messages

#### Tasks

- [x] cerate admin ticket
- [x] create cotent field
- [x] add submit button

#### Acceptance Criteria

- [x] user can type a message to admin
- [x] user can see message is sent in their notification panel
- [x] user can view the message sent
- [x] user can see status of message
