### ISSUE TITLE
User Navigation Bar Update

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/HLL-Clans-encyclopedia#9]
### User Story
As a developer I can update the nav bar links so that depending on the users access they will have certain links added to their nav bar 

#### Tasks

- [x] Create a model for user accounts
- [x] Create a view for user authentication and authorisation
- [x] Create conditional functions in the html template 
- [x] Conditional functions to access user authority and display the result accordingly 

#### Acceptance Criteria

- [x] What appears on the navbar updates depending on the users log in access
- [x] System correctly matches user log in with the access they should have
- [x] Navbar contains functions which link with database
